default = "en"

[app.builder]
try-load = "ModuleBuilder: try to load module '{module_init_path}'"
try-unload = "ModuleBuilder: try to unload module '{module_init_path}'"
load-error = "ModuleBuilder: module initializer error: {exc}"
unload-error = "ModuleBuilder: module finalizer error: {exc}"
validation-error = "ModuleBuilder: validation error occurred during module loading: '{detail]'"
invalid-module-conf = "ModuleBuilder: returned invalid module conf for '{path}'"
load-success = "ModuleBuilder: load module success '{module_init_path}'"
unload-success = "ModuleBuilder: unload module success '{module_init_path}'"
try-create = "ModuleBuilder: try to create module '{path}'"
create-success = "ModuleBuilder: create module success '{path}'"
try-destroy = "ModuleBuilder: try to destroy module '{path}'"
destroy-success = "ModuleBuilder: destroy module success '{path}'"
module-error = "ModuleBuilder: module creation error: {exc}"
module-disabled = "ModuleBuilder: module disabled '{path}'"

try-ctrl = "ModuleBuilder: try to create controller '{name}'"
ctrl-error = "ModuleBuilder: controller creation error: {exc}"
ctrl-success = "ModuleBuilder: controller creation success '{name}'"
ctrl-not-found = "ModuleBuilder: controller factory not found: '{key}'"
ctrl-disabled = "ModuleBuilder: controller disabled '{path}'"

try-service = "ModuleBuilder: try to create service '{name}'"
service-error = "ModuleBuilder: service creation error: {exc}"
service-success = "ModuleBuilder: service creation success '{name}'"
service-not-found = "ModuleBuilder: service factory not found: '{key}'"
service-disabled = "ModuleBuilder: service disabled '{path}'"

[app.application]
try-load = "Application: try to load module '{module_path}'"
try-unload = "Application: try to unload module '{module_path}'"
load-success = "Application: load module success '{module_path}'"
unload-success = "Application: unload module success '{module_path}'"
run-sync-start = "Application '{name}': start sync"
run-async-start = "Application '{name}': start async"
run-sync-stop = "Application '{name}': running sync STOPPED"
run-async-stop = "Application '{name}': running async STOPPED"

[app.entities]
operator-policy-violation = "No policy found in {type} '{name}' configuration for operator '{key}'"
operator-pattern-violation = "No operator found in {type} '{name}' for policy '{key}' with name pattern '{pattern}'"
operator-unused-policy = "Unused policy found in {type} '{name}' for operator '{key}' with name pattern '{pattern}'"
provider-policy-violation = "No policy found in {type} '{name}' configuration for provider '{key}'"
provider-pattern-violation = "No provider found in {type} '{name}' for policy '{key}' with name pattern '{pattern}'"
provider-unused-policy = "Unused policy found in {type} '{name}' for provider '{key}' with name pattern '{pattern}'"
prov-claim-policy-violation = "No policy found in {type} '{name}' configuration for provider claim '{claim_name}'"
dep-failure = "Dependency creation failure in {type} '{name}': {dep_name}"

[app.entities.module]
create-start = "Module '{name}' create"
create-finish = "Module '{name}' created"
destroy-start = "Module '{name}' destroy"
destroy-finish = "Module '{name}' destroyed"
start-start = "Module '{name}' starting"
start-finish = "Module '{name}' started"
stop-start = "Module '{name}' stopping"
stop-finish = "Module '{name}' stopped"
ctrl-created = "Controller '{name}' created"
service-created = "Service '{name}' created"
ctrl-destroyed = "Controller '{name}' destroyed"
service-destroyed = "Service '{name}' destroyed"
ctrl-started = "Controller '{name}' started"
service-started = "Service '{name}' started"
ctrl-stopped = "Controller '{name}' stopped"
service-stopped = "Service '{name}' stopped"
